version: "3.9"

services:
  frontend:
    image: ghcr.io/<owner>/psyexperiments-frontend:latest
    container_name: psyexperiments-frontend
    restart: unless-stopped
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    image: ghcr.io/<owner>/psyexperiments-backend:latest
    container_name: psyexperiments-backend
    environment:
      - OSF_API_TOKEN=${OSF_API_TOKEN}
      - OSF_RESOURCE_ID=${OSF_RESOURCE_ID}
      - HOST_URL=${SERVER_NAME}
    restart: unless-stopped
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  proxy:
    image: ghcr.io/<owner>/psyexperiments-proxy:latest
    container_name: psyexperiments-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - EMAIL=${EMAIL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - frontend
      - backend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    restart: unless-stopped
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    command: --interval 300 --label-enable --include-stopped --include-restarting --rolling-restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  certbot-etc:
  certbot-var:
  dhparam:


